woocommerceAppProject/woocommerceApp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView


app_name = "woocommerceApp"

urlpatterns = [
    path('', views.landing, name="landing"),
    path('dashboard/', views.index, name="index"),
    path('subscription/',views.subscription, name="subscription"),
    path('subscription/list/',views.subscription_list, name="subscription_list"),
    path('subscription/change/<int:id>/',views.subscription_change, name="subscription_change"),
    path('dashboard/schedule/<int:id>/display/',views.schedule_display, name="schedule_display"),
    path('dashboard/schedule/<int:id>/download/', views.get_csv_file, name="download"),
    path('dashboard/schedule/<int:id>/generate/', views.generate_csv_file, name="generate"),
    path('dashboard/schedule/<int:id>/post/', views.woocommerce_post, name="post"),
    path('dashboard/schedule/', views.schedule_creation, name="schedule"),
    path('timezone/', views.set_timezone, name="timezone"),
    path('notification/', views.notification, name="notification"),
    path('signup/',views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

woocommerceAppProject/woocommerceAppProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('woocommerceApp.urls')),

]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

woocommerceAppProject/woocommerceApp/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import *

class ProfileForm(ModelForm):
    photo = forms.ImageField(required=False)

    class Meta:
        model = Profil
        fields = ['photo', 'birthday','gender', 'mailing_Address']
        widgets = {
                'password':forms.PasswordInput(),
                'birthday': forms.DateInput(attrs={'type':'date','class':'form-control'}),
                'mailing_Address':forms.TextInput(attrs= {'class':'form-control'}),


        }

class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {
                'password':forms.PasswordInput(attrs= {'class':'form-control'}),
                'username' : forms.TextInput(attrs= {'class':'form-control'}),
                'first_name' : forms.TextInput(attrs= {'class':'form-control'}),
                'last_name' : forms.TextInput(attrs= {'class':'form-control'}),
                'email' : forms.TextInput(attrs= {'class':'form-control'}),
                'gender' : forms.Select(attrs= {'class': 'form-control'})



        }
        help_texts = {
            'username': '20 characters or fewer. Letters, digits and @/./+/-/_ only.',
        }
class ScheduleForm(ModelForm):

    class Meta:
        model= Schedule
        fields = ['AliExpress_key',
                    'AliExpress_Id',
                    #'AliExpress_fields',
                    'AliExpress_keywords',
                    'AliExpress_category',
                    'AliExpress_Currency',
                    'AliExpress_Increment',
                    'AliExpress_language',
                    'AliExpress_highquality',
                    'woocommerce_url',
                    'woocommerce_consumer_key',
                    'woocommerce_secret_key',

                    ]
        widgets = {
                'AliExpress_key' : forms.TextInput(attrs= {'class':'form-control'}),
                'AliExpress_Id' : forms.TextInput(attrs= {'class':'form-control'}),
                'AliExpress_keywords' : forms.TextInput(attrs= {'class':'form-control'}),
                'AliExpress_category' : forms.Select(attrs= {'class':'form-control'}),
                'AliExpress_highquality' : forms.Select(attrs= {'class':'form-control'}),
                'AliExpress_Currency' : forms.Select(attrs= {'class':'form-control'}),
                'AliExpress_language' : forms.Select(attrs= {'class':'form-control'}),
                'AliExpress_Increment' : forms.TextInput(attrs= {'class':'form-control'}),
                'woocommerce_url' : forms.TextInput(attrs= {'class':'form-control','placeholder':'http://www.example.com/'}),
                'woocommerce_consumer_key' : forms.TextInput(attrs= {'class':'form-control'}),
                'woocommerce_secret_key' : forms.TextInput(attrs= {'class':'form-control'}),


        }

woocommerceAppProject/woocommerceApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from django.core import serializers
from django.core.files import File
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login
from django.forms.models import model_to_dict
from django.forms import modelformset_factory
from django.urls import reverse
from django.utils import timezone
from django.db import transaction
from .models import *
import pytz
import json
import requests
from django.conf import settings
import os
from woocommerce import API
# Create your views here.

@login_required
def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')
    else:
        return render(request, 'woocommerce/timezone.html', {'timezones': pytz.common_timezones})

def landing(request):
    return render(request,"woocommerce/landing.html")

@login_required
def index(request):
    schedules=Schedule.objects.filter(profil__id=request.user.profil.id)
    context = {'schedules': schedules}
    return render(request, "woocommerce/index.html", context)

@login_required
def schedule_creation(request):
    profil = Profil.objects.get(user=request.user)
    subscription = None
    if profil.free_subscription != None:
        subscription = profil.free_subscription
    elif profil.basic_subscription != None:
        subscription = profil.basic_subscription
    elif profil.premium_subscription != None:
        subscription = profil.premium_subscription
    elif profil.gold_subscription != None:
        subscription = profil.gold_subscription

    if subscription.days_time >=1 and subscription.schedules_nb >= 1 and subscription.sites_limites >=1:
        if request.method == 'POST':
            schedule_form = ScheduleForm(request.POST)
            if schedule_form.is_valid():
                schedule = schedule_form.save(commit=False)
                schedule.profil=profil
                schedule.save()
                response = schedule.ali_import()
                schedule.save()
                subscription.schedules_nb=subscription.schedules_nb -1
                subscription.save()
                notification = Notification.objects.create(title='Created',
                    schedule = schedule,
                    profil=profil,
                    link= reverse('woocommerceApp:schedule_display',
                     kwargs={'id':schedule.id}),
                    description='Request ' + str(schedule.id)+ ' has been created !'
                     )
                schedule.save()
                notification.save()
                schedule_form = ScheduleForm()

                context = { 'schedule_form' : schedule_form,
                            'response': response,
                            'schedule': schedule.id,
                            'scrap_done': True
                            }

                return render(request,"woocommerce/schedule_form.html",context)
        else:

            schedule_form = ScheduleForm()


        context = {'schedule_form' : schedule_form,'schedule': 0,
                'scrap_done': False
                }
        return render(request, "woocommerce/schedule_form.html", context)
    else:
        context = {"reject" : "rejected",'schedule': 0,'scrap_done': False}
        return render(request, "woocommerce/schedule_form.html", context)

@login_required
def generate_csv_file(request,id):
    schedule = Schedule.objects.get(pk=id)
    if schedule.file_state == 'P':
        path = settings.MEDIA_ROOT + '/profiles/'+ request.user.username + str(request.user.id) +'/schedule' + str(id)  +'.csv'
        f = open(path, 'w')
        writer = csv.writer(f)
        writer.writerow(['Product ID', 'Product Title', 'Product URL',
                    'Original Price', 'Sale Price','Image URL'])

        path_old = schedule.schedule_file.path
        response_path = os.path.join( settings.BASE_DIR, path_old )
        json_reader = json.loads(open(response_path).read())
        products = json_reader['result']['products']
        for product in products:
            productUrl = product['productUrl']
            productTitle = product['productTitle']
            productId = product['productId']
            originalPrice = product['originalPrice']
            salePrice = product['salePrice']
            incr = Decimal(sub(r'[^\d.]', '', salePrice))
            priceinc = incr * schedule.AliExpress_Increment  # print(incr, priceinc)
            imageUrl = product['imageUrl']
            writer.writerow([productId,productTitle,productUrl,
                            originalPrice,salePrice,imageUrl])
        f.close()
        f = open(path, 'r')
        newFile = ContentFile(f.read())
        schedule.file_state= 'C'
        schedule.schedule_file_csv.save('a.csv',newFile)
        context = { 'schedule': schedule.id,
                    'state' : schedule.file_state

        }
        return render(request,"woocommerce/generate_success.html", context)
    else:
        context = { 'schedule': schedule.id,
                    'state' : schedule.file_state,
                    'post' : False
        }
        return render(request,"woocommerce/generate_success.html", context)


@login_required
def get_csv_file(request,id):
    schedule = Schedule.objects.get(pk=id)
    path = schedule.schedule_file_csv.path
    response_path = os.path.join( settings.BASE_DIR, path )

    f = open(response_path, 'r')
    response = HttpResponse(f,content_type='text/csv')
    schedule.file_state = 'D'
    profil = Profil.objects
    schedule.save()
    response['Content-Disposition'] = 'attachment; filename=%s' %'response'+ str(id)+'.csv'
    return response

@login_required
def woocommerce_post(request,id):
    schedule =  Schedule.objects.get(pk=id)
    wcapi = API(
        url = schedule.woocommerce_url,
        consumer_key = schedule.woocommerce_consumer_key,
        consumer_secret= schedule.woocommerce_secret_key,
        wp_api=True,
        timeout= 100,
        version="wc/v2"
    )
    path = os.path.join(settings.BASE_DIR,schedule.schedule_file.path)
    f = open(path,'r')
    json_file = json.loads(f.read())

    getlistproducts = json_file['result']['products']
    print(getlistproducts)
    for resultsget in getlistproducts:
        producturls = resultsget['productUrl']
        productitles = resultsget['productTitle']
        productids = resultsget['productId']
        originalprices = resultsget['originalPrice']
        saleprices = resultsget['salePrice']
        incr = Decimal(sub(r'[^\d.]', '', saleprices))
        priceinc = incr * 3  # print(incr, priceinc)
        conint = int(priceinc)
        imageurls = resultsget[
            'imageUrl']  # print(productids, productitles,originalprices,saleprices,imageurls, producturls )
        urlpromo = "http://gw.api.alibaba.com/openapi/param2/2/portals.open/api.getPromotionLinks/9420?fields=promotionUrl&trackingId=bazaarmaya"  # GET PROMOTIONAL URL
        payloadpromo = {
            'urls': producturls
        }
        promoget = requests.get(urlpromo, params=payloadpromo)
        promotojson = promoget.text
        promoresult = json.loads(promotojson)
        promourl = promoresult['result']['promotionUrls'][0]['promotionUrl']
        divpromo = "<div class='invisible'>" + promourl + "</div>"
        getdetailsurl = 'http://gw.api.alibaba.com/openapi/param2/2/portals.open/api.getPromotionProductDetail/'  # GET DETAILS
        api_key = '9420'
        fields = '?fields=discount,evaluateScore,commission,commissionRate,30daysCommission,volume,packageType,lotNum,validTime,allImageUrls'
        payloads = {
            'productId': productids
        }
        detailurl = getdetailsurl + api_key + fields
        detailr = requests.get(detailurl, params=payloads)
        getlist = detailr.text
        tojson = json.loads(getlist)
        getresult = tojson['result']
        getdetailvol = getresult['volume']
        getdetailevalscore = getresult['evaluateScore']
        getdetaillotnum = getresult['lotNum']
        getdetaildiscount = getresult['discount']
        getdetailvalid = getresult['validTime']
        getdetailcommision = getresult['30daysCommission']
        getdetailpacktyper = getresult['packageType']
        getdetailallimage = tojson['result']['allImageUrls'].split(',')
        domUrl = "https://www.aliexpress.com/"  # GET DESCRIPTIONS
        dommer = "getDescModuleAjax.htm?productId="
        objecTo = str(productids)
        target = domUrl + dommer + objecTo
        r = requests.get(target)
        mored = r.text
        cutt = mored[29:-5]
        data = {
            "name": productitles,
            "type": "simple",
            "regular_price": str(conint),
            "description": cutt + divpromo,
            "short_description": "",
            "categories": [
                {
                    "id": schedule.AliExpress_category
                }
            ],
            "images": []
        }

        for number, url in enumerate(getdetailallimage):
            data["images"].append({"src": url, "position": number})

        wcapi.post("products", data)
        schedule.file_state = 'PS'
        context = { 'schedule': schedule.id,
                    'state' : schedule.file_state,
                    'post' : True
        }

        return render(request,"woocommerce/generate_success.html", context)


@transaction.atomic
def signup(request):

    if request.user.is_authenticated:
        return redirect(reverse('woocommerceApp:index'))

    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

woocommerceAppProject/woocommerceApp/templates/woocommerce/index.html
{% extends 'woocommerce/baseUser.html' %}
{% block header %}
<title>Dashboard</title>
{% endblock %}
{% load staticfiles %}
{% block content %}
    <div class="" id="wrapper">
      <div class="row">
        <div class="col-lg-1 col-lg-offset-1" style="margin-top: 1em;">
         <div>
         <b>List of requests:</b>
         </div>
        </div>
      </div>
       <div class="row" >
         <div class="col-lg-1" >
         </div>
       <div class="hpanel col-lg-10" style="margin-top: 1em;">

           <div class="panel-body">
             {% if schedules %}
               <div class="table-responsive">
               <table class="table table-hover table-bordered table-striped">
                   <tbody>
                     <thead>
                       <tr>
                          <th>State</th>
                          <th>Request name</th>
                          <th>Website URL</th>
                          <th>Request creation time</th>

                        </tr>
                      </thead>
                  {% for schedule in schedules %}
                   <tr>
                        {% if schedule.file_state == 'P' %}
                       <td>
                         <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">

                           <span class="label label-warning">Pending</span>
                         </a>
                       </td>
                        {% elif schedule.file_state == 'C' %}
                        <td>
                          <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">
                            <span class="label label-success">Created</span>
                          </a>
                        </td>
                        {% elif schedule.file_state == 'D' %}
                        <td>
                          <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">
                            <span class="label label-primary">Downloaded</span>
                          </a>
                        </td>
                        {% elif schedule.file_state == 'PS' %}
                        <td>
                            <span class="label label-primary2">Posted</span>
                        </td>
                        {% endif %}
                       <td class="issue-info">
                         <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">

                               {{schedule.id}}

                           <br/>
                           <small>
                               Keywords: {{schedule.AliExpress_keywords}}, Category: {{schedule.AliExpress_category}}.
                           </small>
                         </a>
                       </td>
                       <td>
                         <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">
                           {{ schedule.woocommerce_url }}
                         </a>
                       </td>
                       <td>
                         <a href="{%url 'woocommerceApp:schedule_display' schedule.id %}">
                           {{ schedule.schedule_start }}
                         </a>
                       </td>
                       </a>
                       <td class="text-center">
                            <a href="{%url 'woocommerceApp:download' schedule.id %}">
                           <button class="btn btn-primary btn-sm"> Download</button>
                           </a>
                       </td>
                   </tr>
                   {%endfor%}
                 </tbody>
               </table>
               </div>
               {% else %}
               <div class="">
                 No requests made yet.
               </div>
               {% endif %}
             </div>
           </div>
           <div class="col-lg-1">

           </div>
         </div>

         <div class="text-center" style="margin-top: 1em; margin-bottom: 1em;">
           <a href="{%url 'woocommerceApp:schedule'%}">

             <button type="button" class="btn btn-success" onclick="request_form()">
               Make a new request
             </button>
           </a>

        </div>

  </div>
  {% block scripts %}
  <script type="text/javascript">

        $.ajax({
          type: "POST",
          url: url,
      //data: {'time': time_filter_list, 'tag': tag_filter_list, 'title':input_value},
        success: function(result) {
              $("#schedule-form").html(result)
            },
        error: function(error) {
              //  alert("ERROR");
        //  console.log(url);
          }
        });

      }
  </script>
  {% endblock %}
{% endblock %}

woocommerceAppProject/woocommerceApp/templates/woocommerce/schedule_display.html
{% extends 'woocommerce/baseUser.html' %}
{% load staticfiles %}
{% block header %}
<title>Request details</title>
{% endblock %}
{% block content %}
<div id="wrapper">
  <div class="row">
      <div class="col-lg-12">
          <div class="hpanel">
              <div class="panel-heading">
                  Results for Request {{schedule.id}}

              </div>
              <div class="panel-body">

                  <table id="example1" class="table table-striped table-bordered table-hover" width="100%">
                      <thead>
                      <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>URL</th>
                        <th width="15%">Price</th>
                        <th width="15%">Sale Price</th>
                        <th width="15%">Image</th>
                      </tr>
                      </thead>
                      <tfoot>
                        <th>ID</th>
                        <th>Title</th>
                        <th>URL</th>
                        <th width="15%">Price</th>
                        <th width="15%">Sale Price</th>
                        <th width="15%">Image</th>
                      </tfoot>
                  </table>
                  <div class="row">

                  </div>
                        {% if schedule.file_state == 'P' %}
                        <a href="{%url 'woocommerceApp:generate' schedule.id %}">
                        <button class="btn btn-primary" type="submit" >Generate CSV file</button>
                        </a>
                        <a href="{%url 'woocommerceApp:post' schedule.id %}">
                        <button class="btn btn-success" type="submit" >Post data to your website</button>
                        </a>
                        {% else %}
                        <a href="{%url 'woocommerceApp:download' schedule.id %}">
                        <button class="btn btn-primary" type="submit" >Download CSV file</button>
                        </a>

                        <a href="{%url 'woocommerceApp:post' schedule.id %}">
                        <button class="btn btn-success" type="submit" >Post data to your website</button>
                        </a>
                        {% endif %}
                    </a>


              </div>
          </div>


      </div>

  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'template/vendor/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- DataTables buttons scripts -->
<script src="{% static 'template/vendor/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'template/vendor/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>

<script>

  $(document).ready(function() {
    $('#example1').DataTable( {
        "processing": true,
        "ajax" :{
           "url":"{{schedule.schedule_file.url}}",
           "dataSrc": function(json){
             return json['result']['products']
           }
         },
        "columns": [
            { "data": "productId" },
            { "data": "productTitle" },
            { "data": "productUrl" },
            { "data": "originalPrice" },
            { "data": "salePrice" },
            { "data": "imageUrl" }
        ]
      } );
} );

</script>

{% endblock %}

woocommerceAppProject/woocommerceApp/templates/woocommerce/schedule_form.html
{% extends 'woocommerce/baseUser.html' %}
{% block header %}
<title>Request creation</title>
{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="" id="wrapper">

<div class="content">
  <div class="row">
      <div class="col-lg-12">
          <div class="hpanel">
              <div class="panel-heading">
                  <div class="panel-tools">

                  </div>
                  Basic elements
              </div>
              <div class="panel-body">
              <form action="{%url 'woocommerceApp:schedule' %}" method="post" class="form-horizontal">
                {% csrf_token %}

                <div class="col-lg-6">
                  <div class="form-group"><label class="col-sm-2 control-label" for="{{schedule_form.id_for_label}}">AliExpress Key</label>
                    <span>{{schedule_form.AliExpress_key.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_key}}</div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-2 control-label">AliExpress Id</label>
                <span>{{schedule_form.AliExpress_Id.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_Id}}</div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-2 control-label">Keywords</label>
                <span>{{schedule_form.AliExpress_keywords.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_keywords}}</div>
              </div>
              <div class="form-group"><label class="col-sm-2 control-label">Language</label>
                <span>{{schedule_form.AliExpress_language.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_language}}</div>
              </div>
              <div class="form-group"><label class="col-sm-2 control-label">High Quality</label>
                <span>{{schedule_form.AliExpress_highquality.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_highquality}}</div>
              </div>

              </div>
              <div class="col-lg-6">
              <div class="form-group"><label class="col-sm-2 control-label">Woocommerce Site Url</label>
                <span>{{schedule_form.woocommerce_url.errors}}</span>

                    <div class="col-sm-10">{{ schedule_form.woocommerce_url}}</div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-3 control-label">Consumer Key</label>
                <span>{{schedule_form.woocommerce_consumer_key.errors}}</span>

                  <div class="col-sm-9">{{ schedule_form.woocommerce_consumer_key}}</div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-3 control-label">Secret key</label>
                <span>{{schedule_form.woocommerce_secret_key.errors}}</span>

                  <div class="col-sm-9">{{ schedule_form.woocommerce_secret_key}}</div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-2 control-label">Categories</label>
                <span>{{schedule_form.AliExpress_category.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_category}}</div>
              </div>
              <div class="form-group"><label class="col-sm-2 control-label">Currency</label>
                  <span>{{schedule_form.AliExpress_Currency.errors}}</span>
                  <div class="col-sm-10">{{ schedule_form.AliExpress_Currency}}</div>
              </div>
              <div class="form-group"><label class="col-sm-2 control-label">Increment</label>
                <span>{{schedule_form.AliExpress_Increment.errors}}</span>

                  <div class="col-sm-10">{{ schedule_form.AliExpress_Increment}}</div>
              </div>
              <div class="form-group">
                  <div class="col-sm-8 col-sm-offset-2">
                      <button class="btn btn-default" type="submit">Cancel</button>
                      <button class="btn btn-primary" type="submit">Save changes</button>
                  </div>
              </div>
              </div>
              </form>

              </div>
          </div>


      </div>

  </div>
  {% if scrap_done %}

  <div class="row">
      <div class="col-lg-12">
          <div class="hpanel">
              <div class="panel-heading">
                  Results

              </div>
              <div class="panel-body">

                  <table id="example1" class="table table-striped table-bordered table-hover" width="100%">
                      <thead>
                      <tr>
                          <th>ID</th>
                          <th>Title</th>
                          <th>URL</th>
                          <th width="15%">Price</th>
                          <th width="15%">Sale Price</th>
                          <th width="15%">Image</th>
                      </tr>
                      </thead>
                      <tfoot>
                        <th>ID</th>
                        <th>Title</th>
                        <th>URL</th>
                        <th width="15%">Price</th>
                        <th width="15%">Sale Price</th>
                        <th width="15%">Image</th>
                      </tfoot>
                  </table>
                  <div class="row">

                  </div>
                        <a href="{%url 'woocommerceApp:generate' schedule %}">
                        <button class="btn btn-primary" type="submit" >Generate CSV file</button>
                        </a>
                        <a href="{%url 'woocommerceApp:post' schedule %}">
                        <button class="btn btn-success" type="submit" >Post data to your website</button>
                        </a>
                    </a>


              </div>
          </div>


      </div>

  </div>
  </div>
  {%endif%}

</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'template/vendor/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- DataTables buttons scripts -->
<script src="{% static 'template/vendor/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'template/vendor/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'template/vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
{% if scrap_done %}
<script>

  $(document).ready(function() {
    $('#example1').DataTable( {
        "processing": true,
        "ajax" :{
           "url":"{{response.url}}",
           "dataSrc": function(json){
             return json['result']['products']
           }
         },
        "columns": [
            { "data": "productId" },
            { "data": "productTitle" },
            { "data": "productUrl" },
            { "data": "originalPrice" },
            { "data": "salePrice" },
            { "data": "imageUrl" }
        ]
      } );
} );

  function csv_req(){
    $.ajax({
      type: "POST",
      url: "{%url 'woocommerceApp:download' schedule %}",
      dataType : "csv",
      data: {'link':"{{response.path}}",
              'id' : "{{schedule}}"
            },
      success : function(result){
        console.log(response);
      },

      error : function(error){
        console.log(error);
      }

    })
  }
</script>
{%endif%}
{% endblock %}